### ISSUE TITLE
Issue with reporting resistance OXA-48

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/microSALT#149] opened 2021-11-26 13:18 UTC
**Describe the bug**
Perfect matches to OXA-48 are no longer reporter in microSALT, instead microSALT reports OXA-566 resistance of lower %identities.

Message from KS in Ticket [722237](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=44975#reply):

> ...angående att OXA-48 har börjat rapporteras som OXA-566 (identity 99,88%). Kör jag fastq-filerna från er i Resfinder så rapporterar den OXA-48 (100% match). Jag skulle då meddela ungefär när denna förändring inträffat och vad jag kan se så rapporteras prov 20ET200231 (Ticket 112544, v44 2020) som OXA-48 medan prov 20ET500236 (Ticket 935485, v47 2020) rapporteras som OXA-566. Är det något som ändrats i assembly under denna period?

**To Reproduce**
1. Run sample 20ET200231 or 20ET500236 with microSALT > 3.1.3 and microSALT 3.1.0

**Expected behavior**
OXA-48 should be reported if this resistances has higher %identity.

**Additional context**
Is OXA-48 in the raw blast results?

Adding some of the commits made during the period below. Has any affected OXA-48 reporting? Scrape_blast changes likely.

- Scrape_blast: [Attempt to make resistance searches more compatible](https://github.com/Clinical-Genomics/microSALT/commit/3f1488cd655fc5e0fd75ef44ebc845475d7f5884)
- Scrape_blast: [Locilengths now ignores reference name](https://github.com/Clinical-Genomics/microSALT/commit/395a218cef8e43681e1d358ea4d68b1ff9a6f5bf)
- Scrape_blast: [Rolledback expec locilength generous lookup](https://github.com/Clinical-Genomics/microSALT/commit/2e626ef3be9440229001911710b0a81e68b8e7ba)
Scrape_blast: [Added padder safety](https://github.com/Clinical-Genomics/microSALT/commit/b4e1231a3901cc9181982f243d7ebbc0ebcbfb45)
- Scrape_blast: [from Clinical-Genomics/resistance-scrape](https://github.com/Clinical-Genomics/microSALT/commit/27e4685e2210c4893b5b99e7c66ab1fc5f4d82ea)
- Referencer: [Updated and fixed bugs in pubmlst and ncbi downloads](https://github.com/Clinical-Genomics/microSALT/commit/9757f6b5690da7dbfec5a1c1d3d3bcb89ab4c661)
- Referencer: [Clarified logic in referencer](https://github.com/Clinical-Genomics/microSALT/commit/7e38873f902c219a3db4dd65fa4dfcb817c2dcad)
- Referencer: [from Clinical-Genomics/fix_referencer](https://github.com/Clinical-Genomics/microSALT/commit/a5742982019f288b21fb26920c9a89470379f787)

**Comment by talnor** [comment] 2021-11-26 13:59
Currently blocked by [installation issues](https://github.com/Clinical-Genomics/microSALT/issues/150)

**Comment by moahaegglund** [comment] 2022-10-19 10:17
No longer blocked, installation issues solved in #142.

**Comment by pbiology** [comment] 2023-06-29 07:53
Will be resolved in Clinical-Genomics/CG-JASEN#5

**Comment by samuell** [comment] 2024-06-19 14:47
Opening this, as it continues to cause problems, and we might need to prioritize it if Jasen is not completed soon.

**Comment by samuell** [comment] 2024-06-19 14:58
I have been running Spades (4.0.0) assembly + Blasting against the resfinder DB semi-manually, using the same commands as used in microSALT, both with and without the `--isolate` flag to Spades, and the OXA-48 gene is reported correctly with both methods.

This thus strengthens the suspicion that the error might be in the scraping logic.

(Unless there are some differences between Spades 3.13.1 used in microSALT right now, and 4.0.0.)

**Comment by samuell** [comment] 2024-06-25 14:53
And in one of these commits:

deed81b57a9301fa9cd87491e71d8f5445f59da9 Removed newline char in log
ab280db6b4c1dd29fb44e04157fa9fb7d809e59d Update pull_request_template.md
7e38873f902c219a3db4dd65fa4dfcb817c2dcad Clarified logic in referencer
9757f6b5690da7dbfec5a1c1d3d3bcb89ab4c661 Updated and fixed bugs in pubmlst and ncbi downloads
27e4685e2210c4893b5b99e7c66ab1fc5f4d82ea Merge pull request #121 from Clinical-Genomics/resistance-scrape
170b013b12cb95ea14bd4bb8f5b115061e16a0d5 Version bump
b4e1231a3901cc9181982f243d7ebbc0ebcbfb45 Added padder safety
5749721faf03743a971341c78fa1650d5e08e330 Quast backwards fix
2e626ef3be9440229001911710b0a81e68b8e7ba Rolledback expec locilength generous lookup
395a218cef8e43681e1d358ea4d68b1ff9a6f5bf Locilengths now ignores reference name
a05ef8949444a89de8d81d25058123e744ae14ce Update __init__.py
3f1488cd655fc5e0fd75ef44ebc845475d7f5884 Attempt to make resistance searches more compatible

**Comment by samuell** [comment] 2024-06-25 16:49
According to a hand-crafted test, the changed behaviour occurs in one of the following commits:

deed81b57a9301fa9cd87491e71d8f5445f59da9 Removed newline char in log
ab280db6b4c1dd29fb44e04157fa9fb7d809e59d Update pull_request_template.md
7e38873f902c219a3db4dd65fa4dfcb817c2dcad Clarified logic in referencer
9757f6b5690da7dbfec5a1c1d3d3bcb89ab4c661 Updated and fixed bugs in pubmlst and ncbi downloads
27e4685e2210c4893b5b99e7c66ab1fc5f4d82ea Merge pull request #121 from Clinical-Genomics/resistance-scrape
170b013b12cb95ea14bd4bb8f5b115061e16a0d5 Version bump
b4e1231a3901cc9181982f243d7ebbc0ebcbfb45 Added padder safety
5749721faf03743a971341c78fa1650d5e08e330 Quast backwards fix
2e626ef3be9440229001911710b0a81e68b8e7ba Rolledback expec locilength generous lookup
395a218cef8e43681e1d358ea4d68b1ff9a6f5bf Locilengths now ignores reference name
a05ef8949444a89de8d81d25058123e744ae14ce Update __init__.py
3f1488cd655fc5e0fd75ef44ebc845475d7f5884 Attempt to make resistance searches more compatible

**Comment by samuell** [comment] 2024-06-26 07:18
It is introduced with this one:

395a218cef8e43681e1d358ea4d68b1ff9a6f5bf Locilengths now ignores reference name

(Tested by cherry-picking the commits one by one into a test branch, using a real-world resistance blast output containing both OXA-566 and OXA-48 instead of the test one, and looking for occurrences of `OXA-48` in `caplog.text`).

**Comment by samuell** [comment] 2024-07-11 20:43
I think I'm starting to have a reasonable test now, that now fails (before implementing the fix), saying:

```log
>     assert "blaOXA-48" in genes
E     assert 'blaOXA-48' in ["aph(3')-III", 'ant(6)-Ia', 'blaOXA-566']
```

(See https://github.com/Clinical-Genomics/microSALT/actions/runs/9898158769/job/27344305202 )

This is triggered by using some real-world example data where both OXA-48 and OXA-566 are included. But re-assuring to see that we reproduce the inclusion of blaOXA-566 there, as the issue described.

**Comment by samuell** [comment] 2024-08-21 09:48
Just for the rec: As can be seen [here](https://github.com/Clinical-Genomics/microSALT/commit/c169d29fe44353bf34079844c7fb6f25f3d8e60b), the cause turned out to be a regex that was too unspecific, so that it would match more than the specified gene name... e.g. searching for `blaVIM-4` would also match `blaVIM-488` or similar. The fix makes the regex more specific by requiring a match against the underscore character coming after the gene name in blast output.

**Closed** 2024-10-11 14:27 UTC
Labels: KS requests, bug
